version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: cryptouser
      POSTGRES_PASSWORD: cryptopass
      POSTGRES_DB: crypto_dashboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: